name = "kangaroo-levelb"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"

[[ d1_databases ]]
binding = "DB"
database_name = "kangaroo-users"
database_id = "b344e14b-940f-49a2-a880-b47685e05d48"
